spring:
  datasource:
    url: jdbc:mariadb://45.124.94.141:3306/boots
    username: hoangpv
    password: hoangpv@789
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port : 8088
